_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  NUM_PROPOSALS: 500
  NUM_CLASSES: 81
  DECORR_WEIGHT: 1.0
  CROWD: True
  CROWD_FUNCTION: "FLCG"
  CROWD_WEIGHT: 0.0
  CROWD_PRIVATE_HARDNESS: 0.8
DATASETS:
  TRAIN: ("my_train",)
  TEST:  ("my_val",)
SOLVER:
  STEPS: (10000,)
  MAX_ITER: 15000
  WARMUP_ITERS: 200
TEST:
  EVAL_PERIOD: 15000
  PREV_INTRODUCED_CLS: 0
  CUR_INTRODUCED_CLS: 20
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
OUTPUT_DIR: "output/M-OWODB/t1/"