_BASE_: "base.yaml"
MODEL:
  WEIGHTS: "output/M-OWODB/t2/model_final.pth"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  NUM_PROPOSALS: 500
  NUM_CLASSES: 81
  DECORR_WEIGHT: 0.0
  CROWD: True
  CROWD_FUNCTION: "FLCG"
  CROWD_WEIGHT: 1e-5
  CROWD_PRIVATE_HARDNESS: 1.0
DATASETS:
  TRAIN: ("my_train",)
  TEST:  ("my_val",)
SOLVER:
  STEPS: (20000, 25000, 27000)
  MAX_ITER: 30000
  WARMUP_ITERS: 0
TEST:
  EVAL_PERIOD: 30000
  PREV_INTRODUCED_CLS: 20
  CUR_INTRODUCED_CLS: 20
  PREV_CLASSES: (20,)
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
OUTPUT_DIR: "output/M-OWODB/t2/"
